translation:
  attachment:
    FileName: contentName
    MimeType: mimeType
    ByteContent: byteContent
  field:
    UID: ediUid
    SENDERGLN: supplierGln
  document:
    Repository: ediRepository
  metadata:
    CreationDate: originCreatedOn
    ReferenceId: ediReferenceId
    TrackId: ediTrackingId
    UID: ediMessageUid

solace:
  java:
    host: "tcp://localhost:55555"
    msgVpn: "default"
    clientUsername: "solace-username"
    clientPassword: "solace-password"
    queueName: "solace-queue"